server:
  port: 8010
spring:
  application:
    name: discovery-service
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    preferIpAddress: true

logging:
  file:
    name: tourist-command.log
