server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

spring:
  application:
    name:
      user-management
  config:
    import: configserver:http://localhost:9011
  sql.init.mode: always
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/tourist_management?createDatabaseIfNotExist=true
    username: user
    password: password

logging:
  file:
    name: users-login.log

