server:
  port: 9011

spring:
  application:
    name:
      TOURIST-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abhijitk7/tourist-management-config.git
          default-label: master
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVICE:localhost}:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}