server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVICE:localhost}:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

spring:
  application:
    name:
      TOURIST-MANAGEMENT-COMMAND
  devtools:
    restart:
      enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: 27017
      database: touristManagement
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVER:localhost}:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,routes,httptrace

logging:
  file:
    name: tourist-command.log


